/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void checkboxLokasyon_clicked1(GCheckbox source, GEvent event) { //_CODE_:checkboxLokasyon:939952:
  println("checkboxLokasyon - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:checkboxLokasyon:939952:

public void checkboxYukseklik_clicked1(GCheckbox source, GEvent event) { //_CODE_:checkboxYukseklik:919125:
  println("checkbox2 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:checkboxYukseklik:919125:

public void sliderZamanlama_change1(GSlider source, GEvent event) { //_CODE_:sliderZamanlama:300012:
  println("sliderZamanlama - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:sliderZamanlama:300012:

public void checkboxBatarya_clicked1(GCheckbox source, GEvent event) { //_CODE_:checkboxBatarya:493573:
  println("checkboxBatarya - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:checkboxBatarya:493573:

public void buttonSend_click1(GButton source, GEvent event) { //_CODE_:buttonSend:872700:
  println("buttonSend - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:buttonSend:872700:

public void textfieldCagriAdi_change1(GTextField source, GEvent event) { //_CODE_:textfieldCagriAdi:558481:
  println("textfieldCagriAdi - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfieldCagriAdi:558481:

public void dropListSSID_click1(GDropList source, GEvent event) { //_CODE_:dropListSSID:560365:
  println("dropListSSID - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:dropListSSID:560365:

public void dropListSembol_click1(GDropList source, GEvent event) { //_CODE_:dropListSembol:606061:
  println("dropListSembol - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:dropListSembol:606061:

public void dropListGPSHizi_click1(GDropList source, GEvent event) { //_CODE_:dropListGPSHizi:549444:
  println("dropListGPSHizi - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:dropListGPSHizi:549444:

public void textfieldMesaj_change1(GTextField source, GEvent event) { //_CODE_:textfieldMesaj:236196:
  println("textfieldMesaj - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfieldMesaj:236196:

public void sliderPreamble_change1(GSlider source, GEvent event) { //_CODE_:sliderPreamble:934008:
  println("sliderPreamble - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:sliderPreamble:934008:

public void sliderTXDelay_change1(GSlider source, GEvent event) { //_CODE_:sliderTXDelay:750989:
  println("sliderTXDelay - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:sliderTXDelay:750989:

public void buttonReceive_click1(GButton source, GEvent event) { //_CODE_:buttonReceive:300015:
  println("buttonReceive - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:buttonReceive:300015:

synchronized public void win_draw2(PApplet appc, GWinData data) { //_CODE_:seriportWindow:303233:
  appc.background(230);
} //_CODE_:seriportWindow:303233:

synchronized public void preSeriportWindow(PApplet appc, GWinData data) { //_CODE_:seriportWindow:982297:
  println("seriportWindow - pre method called " + millis());
} //_CODE_:seriportWindow:982297:

synchronized public void postSeriportWindow(PApplet appc, GWinData data) { //_CODE_:seriportWindow:981943:
  println("seriportWindow - post method called " + millis());
} //_CODE_:seriportWindow:981943:


public void buttonBaglanClick(GButton source, GEvent event) { //_CODE_:buttonBaglan:635785:
  println("buttonBaglan - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:buttonBaglan:635785:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.GOLD_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("hymTR Ayar Programi");
  labelX = new GLabel(this, 20, 20, 80, 20);
  labelX.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  labelX.setText("Cagriadi");
  labelX.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  labelX.setOpaque(true);
  labelY = new GLabel(this, 10, 300, 180, 20);
  labelY.setText("Preamble Suresi (milisaniye)");
  labelY.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  labelY.setOpaque(true);
  label4 = new GLabel(this, 10, 380, 190, 20);
  label4.setText("Kuyruk Suresi (milisaniye)");
  label4.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label4.setOpaque(true);
  label5 = new GLabel(this, 20, 50, 80, 20);
  label5.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  label5.setText("Sembol");
  label5.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label5.setOpaque(true);
  label6 = new GLabel(this, 20, 80, 80, 20);
  label6.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  label6.setText("GPS Port Hizi");
  label6.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label6.setOpaque(true);
  checkboxLokasyon = new GCheckbox(this, 100, 140, 150, 20);
  checkboxLokasyon.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  checkboxLokasyon.setText("Lokasyon");
  checkboxLokasyon.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  checkboxLokasyon.setOpaque(true);
  checkboxLokasyon.addEventHandler(this, "checkboxLokasyon_clicked1");
  checkboxLokasyon.setSelected(true);
  checkboxYukseklik = new GCheckbox(this, 100, 160, 150, 20);
  checkboxYukseklik.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  checkboxYukseklik.setText("Yukseklik");
  checkboxYukseklik.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  checkboxYukseklik.setOpaque(true);
  checkboxYukseklik.addEventHandler(this, "checkboxYukseklik_clicked1");
  sliderZamanlama = new GSlider(this, 10, 240, 440, 47, 10.0);
  sliderZamanlama.setShowValue(true);
  sliderZamanlama.setShowLimits(true);
  sliderZamanlama.setLimits(1, 1, 60);
  sliderZamanlama.setNbrTicks(10);
  sliderZamanlama.setStickToTicks(true);
  sliderZamanlama.setShowTicks(true);
  sliderZamanlama.setNumberFormat(G4P.INTEGER, 0);
  sliderZamanlama.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  sliderZamanlama.setOpaque(true);
  sliderZamanlama.addEventHandler(this, "sliderZamanlama_change1");
  label8 = new GLabel(this, 10, 220, 180, 20);
  label8.setText("Akilli Beacon (Dakika)");
  label8.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label8.setOpaque(true);
  checkboxBatarya = new GCheckbox(this, 100, 180, 150, 20);
  checkboxBatarya.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  checkboxBatarya.setText("Batarya Durumu");
  checkboxBatarya.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  checkboxBatarya.setOpaque(true);
  checkboxBatarya.addEventHandler(this, "checkboxBatarya_clicked1");
  buttonSend = new GButton(this, 230, 460, 220, 30);
  buttonSend.setText("Bilgileri Cihaza Yukle");
  buttonSend.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  buttonSend.addEventHandler(this, "buttonSend_click1");
  textfieldCagriAdi = new GTextField(this, 100, 20, 120, 20, G4P.SCROLLBARS_NONE);
  textfieldCagriAdi.setText("TA7W");
  textfieldCagriAdi.setPromptText("Buraya Cagri Adinizi Giriniz (SSID haric)");
  textfieldCagriAdi.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  textfieldCagriAdi.setOpaque(true);
  textfieldCagriAdi.addEventHandler(this, "textfieldCagriAdi_change1");
  label9 = new GLabel(this, 230, 20, 40, 20);
  label9.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  label9.setText("SSID");
  label9.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label9.setOpaque(true);
  dropListSSID = new GDropList(this, 280, 20, 170, 80, 3, 10);
  dropListSSID.setItems(loadStrings("list_560365"), 3);
  dropListSSID.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  dropListSSID.addEventHandler(this, "dropListSSID_click1");
  dropListSembol = new GDropList(this, 100, 50, 140, 80, 3, 10);
  dropListSembol.setItems(loadStrings("list_606061"), 3);
  dropListSembol.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  dropListSembol.addEventHandler(this, "dropListSembol_click1");
  dropListGPSHizi = new GDropList(this, 100, 80, 90, 80, 3, 10);
  dropListGPSHizi.setItems(loadStrings("list_549444"), 1);
  dropListGPSHizi.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  dropListGPSHizi.addEventHandler(this, "dropListGPSHizi_click1");
  textfieldMesaj = new GTextField(this, 100, 110, 350, 20, G4P.SCROLLBARS_NONE);
  textfieldMesaj.setText("QRV 145.500 Ceptel: 0 5XX XXX XX XX");
  textfieldMesaj.setPromptText("Buraya havaya yayimlanacak mesajinizi yaziniz");
  textfieldMesaj.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  textfieldMesaj.setOpaque(true);
  textfieldMesaj.addEventHandler(this, "textfieldMesaj_change1");
  sliderPreamble = new GSlider(this, 10, 320, 440, 50, 10.0);
  sliderPreamble.setShowValue(true);
  sliderPreamble.setShowLimits(true);
  sliderPreamble.setLimits(350, 100, 1000);
  sliderPreamble.setNbrTicks(20);
  sliderPreamble.setStickToTicks(true);
  sliderPreamble.setShowTicks(true);
  sliderPreamble.setNumberFormat(G4P.INTEGER, 0);
  sliderPreamble.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  sliderPreamble.setOpaque(true);
  sliderPreamble.addEventHandler(this, "sliderPreamble_change1");
  sliderTXDelay = new GSlider(this, 10, 400, 440, 50, 10.0);
  sliderTXDelay.setShowValue(true);
  sliderTXDelay.setShowLimits(true);
  sliderTXDelay.setLimits(100, 50, 500);
  sliderTXDelay.setNbrTicks(9);
  sliderTXDelay.setStickToTicks(true);
  sliderTXDelay.setShowTicks(true);
  sliderTXDelay.setNumberFormat(G4P.INTEGER, 0);
  sliderTXDelay.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  sliderTXDelay.setOpaque(true);
  sliderTXDelay.addEventHandler(this, "sliderTXDelay_change1");
  label10 = new GLabel(this, 20, 140, 80, 20);
  label10.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  label10.setText("Gonder");
  label10.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label10.setOpaque(true);
  label3 = new GLabel(this, 20, 110, 80, 20);
  label3.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  label3.setText("Mesaj");
  label3.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label3.setOpaque(true);
  buttonReceive = new GButton(this, 10, 460, 210, 30);
  buttonReceive.setText("Bilgileri Cihazdan Al");
  buttonReceive.setLocalColorScheme(GCScheme.RED_SCHEME);
  buttonReceive.addEventHandler(this, "buttonReceive_click1");
}

// Variable declarations 
// autogenerated do not edit
GLabel labelX; 
GLabel labelY; 
GLabel label4; 
GLabel label5; 
GLabel label6; 
GCheckbox checkboxLokasyon; 
GCheckbox checkboxYukseklik; 
GSlider sliderZamanlama; 
GLabel label8; 
GCheckbox checkboxBatarya; 
GButton buttonSend; 
GTextField textfieldCagriAdi; 
GLabel label9; 
GDropList dropListSSID; 
GDropList dropListSembol; 
GDropList dropListGPSHizi; 
GTextField textfieldMesaj; 
GSlider sliderPreamble; 
GSlider sliderTXDelay; 
GLabel label10; 
GLabel label3; 
GButton buttonReceive; 
GWindow seriportWindow;
GButton buttonBaglan; 
GLabel label2; 
